version: '2'

volumes:
  dreamfactory-var-lib-mysql: ~

networks:
  default: ~
  plesk:
    external:
      name: plesk_default

services:
  web:
    environment:
      SERVERNAME: dreamfactory.pastis-hosting.net
      DB_HOST: db
      DB_USERNAME: df_admin
      DB_PASSWORD: df_admin
      DB_DATABASE: dreamfactory
      REDIS_HOST: rd
      REDIS_DATABASE: 0
      REDIS_PORT: 6379
    build: .
    links:
      - mysql:db
      - redis:rd
    external_links:
      - plesk_mysql_1:plesk_mysql
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=HostRegexp:dreamfactory.pastis-hosting.net"
      - "traefik.port=80"
      - "traefik.docker.network=dreamfactory_default"
    domainname: pastis-hosting.net
    hostname: dreamfactory
    networks:
      - default
      - plesk

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamfactory
      MYSQL_USER: df_admin
      MYSQL_PASSWORD: df_admin
    image: mysql
    volumes:
      dreamfactory-var-lib-mysql:/var/lib/mysql
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=false"

  redis:
    image: redis
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=false"
