#!/bin/bash

source $PWD/lib.sh

# Fail early
set -e

HOST=${1:-$(hostname)}

log "Starting stacks - hostname=${HOST}"
for stack in ./*; do
    stackName=$(basename $stack)
    if [ -d $stack ]; then
        if [ -f $stack/.servers ] && grep -q ${HOST} $stack/.servers; then
            log "Stack is enabled on host - hostname=${HOST}, stack=${stackName}"
            log "Executing docker-compose up - hostname=${HOST}, stack=${stackName}"
            if [ -f $stack/docker-compose-${HOST}.yml ]; then
                docker-compose -f $stack/docker-compose-${HOST}.yml up -d
                if [ -d $stack/hooks ]; then
                    for hook in $(find $stack/hooks -name '*' -type f); do
                        log "Executing hook - hostname=${HOST}, stack=${stackName}, hook=$(basename $hook)"
                        ( exec $hook up $stack/docker-compose-${HOST}.yml )
                    done
                fi
            elif [ -f $stack/docker-compose.yml ]; then
                docker-compose -f $stack/docker-compose.yml up -d
                if [ -d $stack/hooks ]; then
                    log "Executing hooks - hostname=${HOST}, stack=${stackName}"
                    for hook in $(find $stack/hooks -name '*' -type f); do
                        log "Executing hook - hostname=${HOST}, stack=${stackName}, hook=$(basename $hook)"
                        ( exec $hook up $stack/docker-compose.yml )
                    done
                fi
            fi
        fi
    fi
done
