version: '2'

services:
  glide:
    build: .
    image: fschaper/glide
    
    ports:
      - "8099:80"
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=false"
      # Ça ne fonctionne pas quand on passe par traefik
#      - "traefik.frontend.entryPoints=http"
#      - "traefik.frontend.rule=HostRegexp:glide.pastis-hosting.net"
#      - "traefik.port=80"
#      - "traefik.docker.network=glide_default"
    domainname: pastis-hosting.net
    hostname: glide