version: '2'

volumes:
  plesk-etc: ~
  plesk-opt-psa: ~
  plesk-opt-plesk: ~
  plesk-var-lib-mysql: ~
  plesk-var-lib-plesk: ~
  plesk-var-lib-psa: ~
  plesk-var-parallels: ~
  plesk-var-www: ~

networks:
  default: ~
  solr14:
    external:
      name: solr14_default

services:
  plesk:
    build:
      context: .
      args:
        - MAILJET_API_KEY=8b410c004ac778adb5c990ddf9e51cd3
        - MAILJET_SECRET_KEY=c3c89f60bc6576053e20433f3d4a7e55
    image: pastishosting/plesk
    privileged: true
    expose:
      - "22"
    ports:
     - "8082:80"
     - "443:443"
     - "21:21"
     - "8880:8880"
     - "8443:8443"
     - "2222:22"
     # Passive FTP ports
     - "30000-30009:30000-30009"
    volumes:
      - "plesk-var-www:/var/www"
      - "plesk-var-lib-plesk:/var/lib/plesk"
      - "plesk-var-lib-psa:/var/lib/psa"
      - "plesk-var-lib-mysql:/var/lib/mysql"
      - "plesk-etc:/etc"
      - "plesk-opt-psa:/opt/psa"
      - "plesk-opt-plesk:/opt/plesk"
      - "plesk-var-parallels:/var/parallels"
    links:
      - mysql:mysql.1
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=HostRegexp:{subdomain:.+}.{domain:.+}"
      - "traefik.frontend.priority=1"
      - "traefik.port=80"
      - "traefik.docker.network=plesk_default"
    domainname: pastis-hosting.net
    hostname: plesk
    networks:
      - default
      - solr14

  mysql:
    image: percona
    volumes:
      - "/opt/docker/volumes/mysql.1:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=raoulETalain"
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=false"
