version: '2'

networks:
  default: ~
  plesk:
    external:
      name: plesk_default
  airtime:
    external:
      name: airtime_default
  glide:
    external:
      name: glide_default

services:
  traefik:
    image: traefik:v1.0.2
    restart: always
    volumes:
      - "$PWD/etc/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - airtime
      - default
      - glide
      - plesk
