version: '2'

networks:
  default: ~
  plesk:
    external:
      name: plesk_default
  airtime:
    external:
      name: airtime_default
  dreamfactory:
    external:
      name: dreamfactory_default
  owncloud:
    external:
      name: owncloud_default
  org_incongru_consternationradio:
    external:
      name: org_incongru_consternationradio_default

services:
  traefik:
    image: traefik:v1.0.3

    volumes:
      - "$PWD/etc/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - airtime
      - default
      - dreamfactory
      - owncloud
      - plesk
      - org_incongru_consternationradio
