version: '2'

volumes:
  jenkins-var-jenkins_home: ~

services:
  jenkins:
    image: jenkins
    
    volumes:
      - "jenkins-var-jenkins_home:/var/jenkins_home"
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=HostRegexp:jenkins.pastis-hosting.net"
      - "traefik.port=8080"
      - "traefik.docker.network=jenkins_default"
