version: '2'

services:
  rancher:
    image: rancher/server
    restart: always
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=HostRegexp:rancher.pastis-hosting.net"
      - "traefik.port=8080"
      - "traefik.docker.network=rancher_default"
    domainname: pastis-hosting.net
    hostname: rancher
