version: '2'

volumes:
  chefserver-etc-opscode: ~
  chefserver-var-log-opscode: ~
  chefserver-var-opt-opscode: ~

services:
  chefserver:
    image: quay.io/3ofcoins/chef-server:latest
    labels:
      - "io.rancher.container.network=true"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=HostRegexp:chef.pastis-hosting.net"
      - "traefik.port=80"
      - "traefik.docker.network=chefserver_default"
    environment:
      - "PUBLIC_URL=http://chef.pastis-hosting.net"
    volumes:
      - chefserver-etc-opscode:/etc/opscode
      - chefserver-var-log-opscode:/var/log/opscode:rw
      - chefserver-var-opt-opscode:/var/opt/opscode
    domainname: pastis-hosting.net
    hostname: chef
